extends: base.yaml

tracker:
  hosts:
    static:
      - 44.44.12.1:15003

build_index:
  hosts:
    static:
      - 44.44.12.1:15004

allowed_cidrs:
  - 127.0.0.1
  - 172.17.0.1
  - 172.18.0.1
  - 172.19.0.1

tls:
  name: kraken
  cas:
  - path: /etc/kraken/tls/ca/server.crt
  server:
    disabled: true
    cert:
      path: /etc/kraken/tls/ca/server.crt
    key:
      path: /etc/kraken/tls/ca/server.key
    passphrase:
      path: /etc/kraken/tls/ca/passphrase
  client:
    cert:
      path: /etc/kraken/tls/client/client.crt
    key:
      path: /etc/kraken/tls/client/client.key
    passphrase:
      path: /etc/kraken/tls/client/passphrase
