version: "3"
services:
    routing:
        image: 172.17.0.1:5000/babeld #dm4tze/babeld/dev
        privileged: true
        network_mode: "host"
        container_name: babeld

    agent:
        image: 172.17.0.1:5000/kraken-agent
        restart: always
        privileged: true
        network_mode: "host"
        container_name: kraken_agent
        ports:
            - 16000:16000 #Registry $AGENT_REGISTRY_PORT:$AGENT_REGISTRY_PORT
            - 16001:16001 #Peer ${AGENT_PEER_PORT}:${AGENT_PEER_PORT}
            - 16002:16002 #Server ${AGENT_SERVER_PORT}:${AGENT_SERVER_PORT}
        volumes:
            - /etc/kraken/config/agent/base.yaml:/etc/kraken/config/agent/base.yaml
            - /etc/kraken/config/agent/development.yaml:/etc/kraken/config/agent/development.yaml
        command: /usr/bin/kraken-agent --config=/etc/kraken/config/agent/development.yaml --peer-ip=${HOSTNAME} --peer-port=${AGENT_PEER_PORT} --agent-server-port=${AGENT_SERVER_PORT} --agent-registry-port=${AGENT_REGISTRY_PORT}

    #backend:
        #image: 172.17.0.1:5000/registry
        #container_name: registry
        #network_mode: "host"
        #privileged: true
        #restart: always
        #ports:
            #- 16000:16000

volumes:
    dbdata:
