extends: base.yaml

peerstore:
  redis:
    peer_set_window_size: 1h
    max_peer_set_windows: 5
    addr: 127.0.0.1:14001


origin:
  hosts:
    static:
      - 44.44.12.1:15002

trackerserver:
  announce_interval: 3s

nginx:
  cache_dir: /tmp/kraken-tracker-nginx/

tls:
  name: kraken
  cas:
  - path: /etc/kraken/tls/ca/server.crt
  server:
    disabled: true
    cert:
      path: /etc/kraken/tls/ca/server.crt
    key:
      path: /etc/kraken/tls/ca/server.key
    passphrase:
      path: /etc/kraken/tls/ca/passphrase
  client:
    cert:
      path: /etc/kraken/tls/client/client.crt
    key:
      path: /etc/kraken/tls/client/client.key
    passphrase:
      path: /etc/kraken/tls/client/passphrase
